services:
  api:
    build:
      context: .
      dockerfile: dockerfile.api
    ports:
      - "8000:8000"

  streamlit:
    build:
      context: .
      dockerfile: dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      FASTAPI_URL: http://api:8000
    depends_on:
      - api